const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Pin,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Sin,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Platform.Exps.VectorX,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Exps.VectorY,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.OnObjectClicked
	];
};
self.C3_JsPropNameTable = [
	{Sólido: 0},
	{chaoNormal: 0},
	{Fixar: 0},
	{personagem: 0},
	{lava: 0},
	{moeda: 0},
	{attack1: 0},
	{Plataforma: 0},
	{RestritoAoLayout: 0},
	{personagemColisao: 0},
	{armadilhaInca: 0},
	{PularAtravés: 0},
	{Senóide: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Teclado: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{ganhou: 0},
	{Sprite10: 0},
	{Texto: 0},
	{Sprite11: 0},
	{ChatGPTImage26DeMaiDe202511_05_: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Mouse: 0},
	{pontos: 0},
	{moedas: 0}
];

self.InstanceType = {
	chaoNormal: class extends self.ISpriteInstance {},
	personagem: class extends self.ISpriteInstance {},
	lava: class extends self.ISpriteInstance {},
	moeda: class extends self.ISpriteInstance {},
	personagemColisao: class extends self.ISpriteInstance {},
	armadilhaInca: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	ganhou: class extends self.ITextInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	ChatGPTImage26DeMaiDe202511_05_: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {}
}